version: "3"

services:
    api:
        env_file:
            - ../.env
        environment:
            - DYNAMODB_ENDPOINT=http://dynamodb:8000
            - DYNAMODB_REGION=eu-central-1
            - AWS_ACCESS_KEY_ID=local
            - AWS_SECRET_ACCESS_KEY=local
            - AWS_CONFIG_FILE=
            - AWS_REGION=eu-central-1
        build:
            context: ..
            dockerfile:  $PWD/Dockerfile
        ports:
            - "4000:4000"
            - "9232:9232"
        links:
            - dynamodb
        volumes:
            - ../:/home/node/app/

    dynamodb:
        image: amazon/dynamodb-local:latest
        ports:
            - "8000:8000"

